//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace AssemblyCSharp
{
	public class SquareColors
	{
		public Color RED;
		public Color BLUE;
		public Color YELLOW;
		public Color GREEN;
		public Color PURPLE;
		public Color ORANGE;
		public Color TEAL;
		public Color WHITE;
		public Color PINK;
		public Color GREY;

		public SquareColors ()
		{
			RED = new Color32 (255, 0, 66, 1);
			BLUE = new Color32 (0, 150, 255, 1);
			YELLOW = new Color32 (255, 255, 0, 1);
			GREEN = new Color32 (106, 196, 0, 1);
			PURPLE = new Color32 (115, 0, 200, 1);
			ORANGE = new Color32 (255, 126, 0, 1);
			TEAL = new Color32 (0, 255, 143, 1);
			WHITE = new Color32 (255, 255, 255, 1);
			PINK = new Color32 (228, 0, 255, 1);
			GREY = new Color32 (40, 40, 40, 1);
		}
	}
}

