//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace AssemblyCSharp
{
	public class SquareColors
	{
		public Color LIGHT_PINK;
		public Color YELLOW;
		public Color LIGHT_GREEN;
		public Color PINK;
		public Color TEAL;
		public Color BLUE;
		public Color MAROON;
		public Color PURPLE;
		public Color ORANGE;
		public Color GREEN;

		public SquareColors ()
		{
			LIGHT_PINK = new Color32 (187, 115, 164, 1);
			YELLOW = new Color32 (216, 196, 24, 1);
			LIGHT_GREEN = new Color32 (155, 213, 42, 1);
			PINK = new Color32 (221, 54, 113, 1);
			TEAL = new Color32 (39, 158, 131, 1);
			BLUE = new Color32 (39, 90, 159, 1);
			MAROON = new Color32 (160, 44, 44, 1);
			PURPLE = new Color32 (124, 90, 180, 1);
			ORANGE = new Color32 (188, 117, 79, 1);
			GREEN = new Color32 (96, 143, 68, 1);
		}
	}
}

